print("Macam-Macam Type Data")
print("Boolean ialah menyatakan benar True jika bernilai 1, atau salah False bernilai 0, contoh : False dan True")
print("Float ialah bilangan yang ada koma, contoh : 6.5")
print("Integer ialah bilangan bulat, contoh : 25")
print("String ialah karakter/kalimat yang berupa angka, contoh : mari kita makan bersama")               